application: sopbase
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/1/.*
  script: main.app
  
- url: /old/
  static_files: static/index.html
  upload: static/index\.html

- url: /old/
  static_dir: static

- url: /sencha-touch-2.0.1.1/
  static_dir: sencha-touch-2.0.1.1

- url: /
  static_files: sencha-sop/index.html
  upload: sencha-sop/index\.html

- url: /
  static_dir: sencha-sop

libraries:
- name: django
  version: "1.3"
